# configs/pretrain/libero_vjepa.yaml
app: vjepa
nodes: 1
tasks_per_node: 4
data:
  dataset_type: videodataset  # 改回使用标准视频数据集类型
  datasets:
    - /cephfs/chenshuaixing/data/datasets/libero_files.csv  # CSV文件路径
  data_dir: /cephfs/chenshuaixing/data/datasets/libero_10
  decode_one_clip: true
  batch_size: 16
  num_clips: 1
  num_frames: 16
  tubelet_size: 2
  sampling_rate: 4
  crop_size: 224
  patch_size: 16
  pin_mem: true
  num_workers: 8

data_aug:
  auto_augment: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 0.75
  - 1.35
  random_resize_scale:
  - 0.3
  - 1.0
  reprob: 0.0
logging:
  folder: /cephfs/chenshuaixing/checkpoints/vjepa_libero/
  write_tag: vjepa_libero
loss:
  loss_exp: 1.0
  reg_coeff: 0.0
  # 添加动作预测损失权重
  action_loss_weight: 0.5
mask:
  - aspect_ratio:
      - 0.75
      - 1.5
    num_blocks: 8
    spatial_scale:
      - 0.15
      - 0.15
    temporal_scale:
      - 1.0
      - 1.0
    max_temporal_keep: 1.0
    max_keep: null
  - aspect_ratio:
      - 0.75
      - 1.5
    num_blocks: 2
    spatial_scale:
      - 0.7
      - 0.7
    temporal_scale:
      - 1.0
      - 1.0
    max_temporal_keep: 1.0
    max_keep: null
meta:
  load_checkpoint: true  # 加载预训练的V-JEPA权重
  read_checkpoint: /path/to/vjepa_pretrained_weights.pth  # 预训练权重路径
  seed: 234
  eval_freq: 10  # 增加评估频率
  use_sdpa: true
  dtype: float32  # 使用float32避免训练不稳定
model:
  model_name: vit_large  # 使用ViT-Large架构
  pred_depth: 12
  pred_embed_dim: 384
  uniform_power: true
  use_mask_tokens: true
  zero_init_mask_tokens: true
  # 添加动作预测头配置
  action_predictor:
    enabled: true
    hidden_dim: 512
    output_dim: 7  # 对应Libero数据集的7维动作
optimization:
  ipe: 100  # 减少迭代次数
  ipe_scale: 1.25
  clip_grad: 10.0
  weight_decay: 0.04
  final_weight_decay: 0.4
  epochs: 50  # 减少训练轮数
  warmup: 5  # 减少预热轮数
  start_lr: 0.0001
  lr: 0.0003
  final_lr: 1.0e-06
  ema:
  - 0.998
  - 1.0