app: vjepa
nodes: 1
tasks_per_node: 1
data:
  dataset_type: VideoDataset
  datasets:
    - /cephfs/chenshuaixing/data/libero_video/libero_10/libero_train.csv
  decode_one_clip: true
  batch_size: 8   # 较小的batch_size以适应更大的模型
  num_clips: 1
  num_frames: 16
  tubelet_size: 2
  sampling_rate: 2
  crop_size: 224  # 保持与预训练模型一致
  patch_size: 16
  pin_mem: true
  num_workers: 8
  filter_short_videos: false
  clip_duration: null
data_aug:
  auto_augment: false
  motion_shift: true
  random_resize_aspect_ratio:
  - 0.75
  - 1.35
  random_resize_scale:
  - 0.3
  - 1.0
  reprob: 0.25
logging:
  folder: /cephfs/chenshuaixing/vjepa_logs/libero_kitchen_finetune/
  write_tag: jepa_libero_ft
loss:
  loss_exp: 1.0
  reg_coeff: 0.0
mask:
  - aspect_ratio:
      - 0.75
      - 1.5
    num_blocks: 4
    spatial_scale:
      - 0.15
      - 0.15
    temporal_scale:
      - 1.0
      - 1.0
    max_temporal_keep: 1.0
    max_keep: null
  - aspect_ratio:
      - 0.75
      - 1.5
    num_blocks: 1
    spatial_scale:
      - 0.7
      - 0.7
    temporal_scale:
      - 1.0
      - 1.0
    max_temporal_keep: 1.0
    max_keep: null
meta:
  load_checkpoint: true  # 启用加载预训练模型
  read_checkpoint: "/cephfs/chenshuaixing/checkpoints/v-jepa/pretrain/vit-h-224/vith16.pth.tar"  # 指定预训练模型路径
  seed: 234
  eval_freq: 5
  use_sdpa: true
  dtype: float32
model:
  model_name: vit_huge  # 使用vit_huge模型以匹配预训练权重
  pred_depth: 12
  pred_embed_dim: 384
  uniform_power: true
  use_mask_tokens: true
  zero_init_mask_tokens: true
optimization:
  ipe: 50
  ipe_scale: 1.25
  clip_grad: 1.0  # 降低梯度裁剪阈值以避免大更新
  weight_decay: 0.01  # 降低权重衰减
  final_weight_decay: 0.1
  epochs: 10  # 微调通常需要的epoch较少
  warmup: 2  # 较短的预热期
  start_lr: 0.00005  # 较低的起始学习率
  lr: 0.0001  # 较低的学习率
  final_lr: 1.0e-06
  ema:
  - 0.998
  - 1.0
finetune:  # 添加微调特定配置
  freeze_layers: 24  # 可以冻结前24层，只微调最后8层(共32层)
  train_mask_tokens: true  # 训练掩码令牌