app: vjepa
task: finetune
nodes: 1
tasks_per_node: 1
data:
  dataset_type: VideoDataset
  datasets:
    - /cephfs/chenshuaixing/data/libero_video/libero_10/libero_train.csv
  decode_one_clip: true
  batch_size: 16
  num_clips: 1
  num_frames: 16
  tubelet_size: 2
  sampling_rate: 2
  crop_size: 224
  patch_size: 16
  pin_mem: true
  num_workers: 8
  filter_short_videos: false
  clip_duration: null
data_aug:
  auto_augment: false
  motion_shift: true
  random_resize_aspect_ratio:
  - 0.75
  - 1.35
  random_resize_scale:
  - 0.3
  - 1.0
  reprob: 0.25
logging:
  folder: /cephfs/chenshuaixing/vjepa_logs/libero_kitchen_finetune/
  write_tag: jepa_libero
loss:
  loss_exp: 1.0
  reg_coeff: 0.0
mask:
  - aspect_ratio:
      - 0.75
      - 1.5
    num_blocks: 4
    spatial_scale:
      - 0.15
      - 0.15
    temporal_scale:
      - 1.0
      - 1.0
    max_temporal_keep: 1.0
    max_keep: null
  - aspect_ratio:
      - 0.75
      - 1.5
    num_blocks: 1
    spatial_scale:
      - 0.7
      - 0.7
    temporal_scale:
      - 1.0
      - 1.0
    max_temporal_keep: 1.0
    max_keep: null
meta:
  load_checkpoint: true
  read_checkpoint: "/cephfs/chenshuaixing/checkpoints/v-jepa/pretrain/vit-l-224/vitl16.pth.tar"
  seed: 234
  eval_freq: 10
  use_sdpa: true
  dtype: float32
model:
  model_name: vit_large
  pred_depth: 12
  pred_embed_dim: 384
  uniform_power: true
  use_mask_tokens: true
  zero_init_mask_tokens: true
optimization:
  ipe: 50
  ipe_scale: 1.25
  clip_grad: 10.0
  weight_decay: 0.04
  final_weight_decay: 0.4
  epochs: 20
  warmup: 10
  start_lr: 0.0002
  lr: 0.0005
  final_lr: 1.0e-06
  ema:
  - 0.998
  - 1.0