nodes: 1
tasks_per_node: 1
tag: libero-eval
eval_name: video_classification_frozen
resume_checkpoint: false
data:
  dataset_train: /cephfs/chenshuaixing/data/libero_video/libero_10/libero_train.csv
  dataset_val: /cephfs/chenshuaixing/data/libero_video/libero_10/libero_test.csv
  dataset_type: VideoDataset
  num_classes: 4  # 您的场景数量(SCENE3,4,6,8)
  frames_per_clip: 16
  num_segments: 1
  num_views_per_segment: 1
  frame_step: 2
optimization:
  attend_across_segments: true
  num_epochs: 10
  resolution: 224
  batch_size: 8
  weight_decay: 0.01
  lr: 0.001
  start_lr: 0.001
  final_lr: 0.0
  warmup: 0.
  use_bfloat16: false
pretrain:
  model_name: vit_base  # 与您训练时使用的模型匹配
  checkpoint_key: target_encoder
  clip_duration: null
  frames_per_clip: 16
  tubelet_size: 2
  uniform_power: true
  use_silu: false
  tight_silu: false
  use_sdpa: true
  patch_size: 16
  folder: /cephfs/chenshuaixing/vjepa_logs/libero_kitchen/
  checkpoint: jepa_libero-latest.pth.tar  # 您预训练的模型
  write_tag: jepa_libero_eval